"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 23:58:50.538643
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('base_price', sa.BigInteger(), nullable=False),
    sa.Column('beta', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('volatility', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hq_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('current_day', sa.SmallInteger(), nullable=False),
    sa.Column('current_tick', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('max_day', sa.SmallInteger(), nullable=False),
    sa.Column('start_cash', sa.BigInteger(), nullable=False),
    sa.Column('cash', sa.BigInteger(), nullable=False),
    sa.Column('fee_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('final_total', sa.BigInteger(), nullable=True),
    sa.Column('final_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'FINISHED', 'ABANDONED')", name='status_valid'),
    sa.CheckConstraint('cash >= 0', name='cash_not_negative'),
    sa.CheckConstraint('current_day BETWEEN 1 AND max_day', name='day_in_range'),
    sa.CheckConstraint('current_tick BETWEEN 0 AND 78', name='tick_in_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('games_leaderboard', 'games', ['status', sa.literal_column('final_total DESC')], unique=False)
    op.create_index('games_one_active_per_user', 'games', ['user_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('game_tick', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('event_key', sa.Text(), nullable=True),
    sa.Column('impacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prices_at', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_snapshots',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('holdings',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name='qty_positive'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('game_id', 'stock_code')
    )
    op.create_table('market_daily',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('index_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fx', sa.Numeric(precision=8, scale=1), nullable=False),
    sa.Column('oil', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'day')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=True),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reject_code', sa.Text(), nullable=True),
    sa.Column('reject_message', sa.Text(), nullable=True),
    sa.Column('client_order_id', sa.Text(), nullable=True),
    sa.Column('game_day', sa.SmallInteger(), nullable=False),
    sa.Column('game_tick', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'REJECTED') = (reject_code IS NOT NULL)", name='reject_has_reason'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='side_valid'),
    sa.CheckConstraint("status IN ('FILLED', 'REJECTED')", name='status_valid'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'client_order_id', name='orders_idempotency')
    )
    op.create_index('orders_game', 'orders', ['game_id', 'id'], unique=False)
    op.create_table('portfolio_history',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('cash', sa.BigInteger(), nullable=False),
    sa.Column('stock_value', sa.BigInteger(), nullable=False),
    sa.Column('allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('total = cash + stock_value', name='total_adds_up'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'day')
    )
    op.create_table('stock_prices',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('open', sa.BigInteger(), nullable=False),
    sa.Column('high', sa.BigInteger(), nullable=False),
    sa.Column('low', sa.BigInteger(), nullable=False),
    sa.Column('close', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('low <= open AND low <= close AND high >= open AND high >= close', name='ohlc_consistent'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('game_id', 'stock_code', 'day')
    )
    op.create_table('news',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('game_tick', sa.SmallInteger(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('factor', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), server_default='', nullable=False),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('lon', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('domestic', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("kind IN ('event', 'preview', 'info')", name='kind_valid'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'seq', name='news_seq_per_game')
    )
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee', sa.BigInteger(), nullable=False),
    sa.Column('tax', sa.BigInteger(), nullable=False),
    sa.Column('realized_pnl', sa.BigInteger(), nullable=True),
    sa.Column('cash_after', sa.BigInteger(), nullable=False),
    sa.Column('game_day', sa.SmallInteger(), nullable=False),
    sa.Column('game_tick', sa.SmallInteger(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(side = 'SELL') = (realized_pnl IS NOT NULL)", name='pnl_only_on_sell'),
    sa.CheckConstraint('amount = price * qty', name='amount_matches'),
    sa.CheckConstraint('qty > 0 AND price > 0 AND fee >= 0 AND tax >= 0', name='amounts_valid'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('trades_game', 'trades', ['game_id', 'id'], unique=False)
    op.create_table('news_stocks',
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('news_id', 'stock_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_stocks')
    op.drop_index('trades_game', table_name='trades')
    op.drop_table('trades')
    op.drop_table('news')
    op.drop_table('stock_prices')
    op.drop_table('portfolio_history')
    op.drop_index('orders_game', table_name='orders')
    op.drop_table('orders')
    op.drop_table('market_daily')
    op.drop_table('holdings')
    op.drop_table('game_snapshots')
    op.drop_table('events')
    op.drop_index('games_one_active_per_user', table_name='games', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('games_leaderboard', table_name='games')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
