"""table and column comments

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 00:35:51.097413
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'id',
               existing_type=sa.BIGINT(),
               comment='사건 ID',
               existing_nullable=False)
    op.alter_column('events', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('events', 'day',
               existing_type=sa.SMALLINT(),
               comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('events', 'game_tick',
               existing_type=sa.SMALLINT(),
               comment='게임 속 시각: 그날 몇 번째 5분인지 (0 = 09:00, 78 = 15:30)',
               existing_nullable=False)
    op.alter_column('events', 'type',
               existing_type=sa.TEXT(),
               comment='macro 거시 / corp 기업 공시 / rate 금리 결정 / earnings 실적 / trial 임상 / rumor 루머 / preview 예고',
               existing_nullable=False)
    op.alter_column('events', 'event_key',
               existing_type=sa.TEXT(),
               comment='사건 종류 키 (simulator/catalog.py, 예: oil_up)',
               existing_nullable=True)
    op.alter_column('events', 'impacts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='종목별 예상 효과 {종목 코드: %}. 투자 성향 분석(뒤늦은 추격 매수)에 사용',
               existing_nullable=False)
    op.alter_column('events', 'prices_at',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='사건이 공개된 순간의 종목 가격 {종목 코드: 원}',
               existing_nullable=False)
    op.create_table_comment(
        'events',
        '공개된 사건과 그 영향. 아직 일어나지 않은 사건은 기록하지 않는다 (공정성)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('game_snapshots', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('game_snapshots', 'day',
               existing_type=sa.SMALLINT(),
               comment='저장한 거래일',
               existing_nullable=False)
    op.alter_column('game_snapshots', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='엔진 상태 전체 (simulator/engine.py 의 게임 상태 dict)',
               existing_nullable=False)
    op.alter_column('game_snapshots', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='저장 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'game_snapshots',
        '복구 지점: 장이 열린 직후의 엔진 상태. Redis 상태가 사라지면 여기서 되살린다',
        existing_comment=None,
        schema=None
    )
    op.alter_column('games', 'id',
               existing_type=sa.BIGINT(),
               comment='게임 ID',
               existing_nullable=False)
    op.alter_column('games', 'user_id',
               existing_type=sa.BIGINT(),
               comment='플레이어 (users.id)',
               existing_nullable=False)
    op.alter_column('games', 'seed',
               existing_type=sa.BIGINT(),
               comment='시장 난수 시드. 같은 시드면 같은 가격·사건이 재현된다 (복구에 사용)',
               existing_nullable=False)
    op.alter_column('games', 'status',
               existing_type=sa.TEXT(),
               comment='ACTIVE 진행 중 / FINISHED 끝까지 마침 / ABANDONED 새 게임을 시작해 포기',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('games', 'current_day',
               existing_type=sa.SMALLINT(),
               comment='현재 거래일 (1 ~ max_day)',
               existing_nullable=False)
    op.alter_column('games', 'current_tick',
               existing_type=sa.SMALLINT(),
               comment='현재 시각(틱). Redis 상태가 사라지면 장 시작 지점부터 여기까지 다시 돌려 복구',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('games', 'max_day',
               existing_type=sa.SMALLINT(),
               comment='게임 길이 (거래일)',
               existing_nullable=False)
    op.alter_column('games', 'start_cash',
               existing_type=sa.BIGINT(),
               comment='시작 자금 (원)',
               existing_nullable=False)
    op.alter_column('games', 'cash',
               existing_type=sa.BIGINT(),
               comment='현재 예수금 (원). 돈의 원본은 이 컬럼이며 Redis 값은 읽을 때마다 여기에 맞춘다',
               existing_nullable=False)
    op.alter_column('games', 'fee_rate',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               comment='매매 수수료율 (매수·매도 각각, 예: 0.00015 = 0.015%)',
               existing_nullable=False)
    op.alter_column('games', 'tax_rate',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               comment='거래세율 (매도만, 예: 0.002 = 0.2%)',
               existing_nullable=False)
    op.alter_column('games', 'final_total',
               existing_type=sa.BIGINT(),
               comment='최종 총자산 (원). 끝난 게임만',
               existing_nullable=True)
    op.alter_column('games', 'final_return_pct',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='최종 수익률 (%). 끝난 게임만',
               existing_nullable=True)
    op.alter_column('games', 'profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='투자 성향 분석 요약 (스타일·점수·특징). 끝난 게임만',
               existing_nullable=True)
    op.alter_column('games', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='시작 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('games', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='끝난(또는 포기한) 시각',
               existing_nullable=True)
    op.create_table_comment(
        'games',
        '게임 한 판. 예수금의 원본. 상태를 바꾸는 요청은 모두 이 행을 SELECT … FOR UPDATE로 잠그고 처리한다',
        existing_comment=None,
        schema=None
    )
    op.alter_column('holdings', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('holdings', 'stock_code',
               existing_type=sa.TEXT(),
               comment='종목 코드 (stocks.code)',
               existing_nullable=False)
    op.alter_column('holdings', 'qty',
               existing_type=sa.BIGINT(),
               comment='보유 수량 (주). 0이 되면 행을 지운다',
               existing_nullable=False)
    op.alter_column('holdings', 'avg_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment='평균 매수가 (원, 수수료 제외한 체결가 기준)',
               existing_nullable=False)
    op.alter_column('holdings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 변경 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'holdings',
        '보유 종목 (게임별 잔고)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('market_daily', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('market_daily', 'day',
               existing_type=sa.SMALLINT(),
               comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('market_daily', 'index_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='종합지수 (게임 시작 전날 = 1,000)',
               existing_nullable=False)
    op.alter_column('market_daily', 'base_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='기준금리 (%)',
               existing_nullable=False)
    op.alter_column('market_daily', 'fx',
               existing_type=sa.NUMERIC(precision=8, scale=1),
               comment='원·달러 환율 (원)',
               existing_nullable=False)
    op.alter_column('market_daily', 'oil',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment='국제유가 (달러/배럴)',
               existing_nullable=False)
    op.create_table_comment(
        'market_daily',
        '장 마감 기준 시장 지표',
        existing_comment=None,
        schema=None
    )
    op.alter_column('news', 'id',
               existing_type=sa.BIGINT(),
               comment='뉴스 ID',
               existing_nullable=False)
    op.alter_column('news', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('news', 'event_id',
               existing_type=sa.BIGINT(),
               comment='이 뉴스를 만든 사건 (events.id). 안내·금리 예고처럼 가격 영향이 없으면 NULL',
               existing_nullable=True)
    op.alter_column('news', 'seq',
               existing_type=sa.INTEGER(),
               comment='게임 안 뉴스 순번 (1부터). 새 뉴스만 받을 때 ?since= 기준',
               existing_nullable=False)
    op.alter_column('news', 'day',
               existing_type=sa.SMALLINT(),
               comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('news', 'game_tick',
               existing_type=sa.SMALLINT(),
               comment='게임 속 시각: 그날 몇 번째 5분인지 (0 = 09:00, 78 = 15:30)',
               existing_nullable=False)
    op.alter_column('news', 'time',
               existing_type=sa.TEXT(),
               comment='화면에 보이는 시각 (예: 10:35, 아침 브리핑은 08:30)',
               existing_nullable=False)
    op.alter_column('news', 'kind',
               existing_type=sa.TEXT(),
               comment='event 사건 / preview 일정 예고 / info 안내',
               existing_nullable=False)
    op.alter_column('news', 'tag',
               existing_type=sa.TEXT(),
               comment='분류 표시 (금리·환율·유가·공시·실적·루머 등)',
               existing_nullable=False)
    op.alter_column('news', 'factor',
               existing_type=sa.TEXT(),
               comment='관련 가격변동 요인 (/factors 페이지의 항목 id)',
               existing_nullable=True)
    op.alter_column('news', 'title',
               existing_type=sa.TEXT(),
               comment='제목',
               existing_nullable=False)
    op.alter_column('news', 'body',
               existing_type=sa.TEXT(),
               comment='본문',
               existing_nullable=False)
    op.alter_column('news', 'why',
               existing_type=sa.TEXT(),
               comment='해설: 왜 이런 종목이 오르고 내리는지',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('news', 'place',
               existing_type=sa.TEXT(),
               comment='사건 장소 이름 (지도 핀)',
               existing_nullable=True)
    op.alter_column('news', 'lat',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='위도',
               existing_nullable=True)
    op.alter_column('news', 'lon',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='경도',
               existing_nullable=True)
    op.alter_column('news', 'domestic',
               existing_type=sa.BOOLEAN(),
               comment='국내 사건이면 true (국내 지도에 핀)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'news',
        '플레이어에게 공개된 뉴스',
        existing_comment=None,
        schema=None
    )
    op.alter_column('news_stocks', 'news_id',
               existing_type=sa.BIGINT(),
               comment='뉴스 ID (news.id)',
               existing_nullable=False)
    op.alter_column('news_stocks', 'stock_code',
               existing_type=sa.TEXT(),
               comment='종목 코드 (stocks.code)',
               existing_nullable=False)
    op.create_table_comment(
        'news_stocks',
        '뉴스 ↔ 관련 종목 (다대다)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('orders', 'id',
               existing_type=sa.BIGINT(),
               comment='주문 ID',
               existing_nullable=False)
    op.alter_column('orders', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('orders', 'stock_code',
               existing_type=sa.TEXT(),
               comment='종목 코드 (stocks.code). 없는 종목으로 거부된 주문이면 NULL',
               existing_nullable=True)
    op.alter_column('orders', 'side',
               existing_type=sa.TEXT(),
               comment='BUY 매수 / SELL 매도',
               existing_nullable=False)
    op.alter_column('orders', 'qty',
               existing_type=sa.BIGINT(),
               comment='주문 수량 (주)',
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.TEXT(),
               comment='FILLED 체결 / REJECTED 거부',
               existing_nullable=False)
    op.alter_column('orders', 'reject_code',
               existing_type=sa.TEXT(),
               comment='거부 사유 코드: INSUFFICIENT_CASH, INSUFFICIENT_QTY, MARKET_CLOSED, UNKNOWN_STOCK 등',
               existing_nullable=True)
    op.alter_column('orders', 'reject_message',
               existing_type=sa.TEXT(),
               comment='거부 사유 (화면에 보여 준 문장)',
               existing_nullable=True)
    op.alter_column('orders', 'client_order_id',
               existing_type=sa.TEXT(),
               comment='클라이언트가 붙인 주문 번호. 같은 게임에서 같은 값이 다시 오면 새로 체결하지 않음 (중복 제출 방지)',
               existing_nullable=True)
    op.alter_column('orders', 'game_day',
               existing_type=sa.SMALLINT(),
               comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('orders', 'game_tick',
               existing_type=sa.SMALLINT(),
               comment='게임 속 시각: 그날 몇 번째 5분인지 (0 = 09:00, 78 = 15:30)',
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='접수 시각 (실제 시각)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'orders',
        '주문. 거부된 주문도 사유와 함께 남긴다 (감사 추적)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('portfolio_history', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'day',
               existing_type=sa.SMALLINT(),
               comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'total',
               existing_type=sa.BIGINT(),
               comment='장 마감 총자산 (원) = 예수금 + 주식 평가액',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'cash',
               existing_type=sa.BIGINT(),
               comment='장 마감 예수금 (원)',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'stock_value',
               existing_type=sa.BIGINT(),
               comment='장 마감 주식 평가액 (원, 종가 기준)',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'allocation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='종목별 평가액 {종목 코드: 원}',
               existing_nullable=False)
    op.create_table_comment(
        'portfolio_history',
        '장 마감 기준 일별 자산 (자산 그래프·최대 낙폭 계산)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('stock_prices', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'stock_code',
               existing_type=sa.TEXT(),
               comment='종목 코드 (stocks.code)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'day',
               existing_type=sa.SMALLINT(),
               comment='거래일. 0 이하는 게임 시작 전 30일 차트 (0 = 시작 전날)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.BIGINT(),
               comment='시가 (원) = 전날 종가',
               existing_nullable=False)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.BIGINT(),
               comment='고가 (원)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.BIGINT(),
               comment='저가 (원)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.BIGINT(),
               comment='종가 (원)',
               existing_nullable=False)
    op.create_table_comment(
        'stock_prices',
        '게임별 일봉 (장 마감 때 기록). 장중 5분 가격은 Redis에만 있다',
        existing_comment=None,
        schema=None
    )
    op.alter_column('stocks', 'code',
               existing_type=sa.TEXT(),
               comment='종목 코드 (예: HBS)',
               existing_nullable=False)
    op.alter_column('stocks', 'name',
               existing_type=sa.TEXT(),
               comment='종목 이름 (예: 한빛반도체)',
               existing_nullable=False)
    op.alter_column('stocks', 'sector',
               existing_type=sa.TEXT(),
               comment='업종. 금리·환율·유가·경기 민감도가 업종별로 다르다',
               existing_nullable=False)
    op.alter_column('stocks', 'base_price',
               existing_type=sa.BIGINT(),
               comment='게임 시작 가격의 기준값 (원). 실제 시작가는 ±10% 무작위',
               existing_nullable=False)
    op.alter_column('stocks', 'beta',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='베타: 시장 전체가 1% 움직일 때 평균 몇 % 움직이는지',
               existing_nullable=False)
    op.alter_column('stocks', 'volatility',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='하루 변동성 (%, 표준편차)',
               existing_nullable=False)
    op.alter_column('stocks', 'description',
               existing_type=sa.TEXT(),
               comment='회사 소개',
               existing_nullable=False)
    op.alter_column('stocks', 'hq_name',
               existing_type=sa.TEXT(),
               comment='본사 위치 (국내 지도 핀)',
               existing_nullable=False)
    op.create_table_comment(
        'stocks',
        '가상 종목 마스터. 원본은 simulator/catalog.py 이고 앱이 시작할 때 이 테이블을 맞춘다',
        existing_comment=None,
        schema=None
    )
    op.alter_column('trades', 'id',
               existing_type=sa.BIGINT(),
               comment='체결 ID',
               existing_nullable=False)
    op.alter_column('trades', 'order_id',
               existing_type=sa.BIGINT(),
               comment='주문 ID (orders.id). 주문 하나에 체결 하나',
               existing_nullable=False)
    op.alter_column('trades', 'game_id',
               existing_type=sa.BIGINT(),
               comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('trades', 'stock_code',
               existing_type=sa.TEXT(),
               comment='종목 코드 (stocks.code)',
               existing_nullable=False)
    op.alter_column('trades', 'side',
               existing_type=sa.TEXT(),
               comment='BUY 매수 / SELL 매도',
               existing_nullable=False)
    op.alter_column('trades', 'qty',
               existing_type=sa.BIGINT(),
               comment='체결 수량 (주)',
               existing_nullable=False)
    op.alter_column('trades', 'price',
               existing_type=sa.BIGINT(),
               comment='체결가 (원)',
               existing_nullable=False)
    op.alter_column('trades', 'amount',
               existing_type=sa.BIGINT(),
               comment='체결금액 = 체결가 × 수량 (원)',
               existing_nullable=False)
    op.alter_column('trades', 'fee',
               existing_type=sa.BIGINT(),
               comment='수수료 (원, 원 미만 버림)',
               existing_nullable=False)
    op.alter_column('trades', 'tax',
               existing_type=sa.BIGINT(),
               comment='거래세 (원, 매도만, 원 미만 버림)',
               existing_nullable=False)
    op.alter_column('trades', 'realized_pnl',
               existing_type=sa.BIGINT(),
               comment='실현손익 (원, 매도만) = 체결금액 − 수수료 − 거래세 − 평균 매수가 × 수량',
               existing_nullable=True)
    op.alter_column('trades', 'cash_after',
               existing_type=sa.BIGINT(),
               comment='체결 직후 예수금 (원). 체결을 순서대로 더하면 이 값과 일치해야 한다',
               existing_nullable=False)
    op.alter_column('trades', 'game_day',
               existing_type=sa.SMALLINT(),
               comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('trades', 'game_tick',
               existing_type=sa.SMALLINT(),
               comment='게임 속 시각: 그날 몇 번째 5분인지 (0 = 09:00, 78 = 15:30)',
               existing_nullable=False)
    op.alter_column('trades', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='체결 시각 (실제 시각)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'trades',
        '체결 (원장). 시장가 즉시 체결이라 주문 하나에 체결 하나',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               comment='회원 ID',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               comment='로그인 아이디 (3~30자, 중복 불가)',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               comment='비밀번호 해시 (werkzeug scrypt 형식, 평문 저장 안 함)',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='가입 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'users',
        '회원',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='회원',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='가입 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='비밀번호 해시 (werkzeug scrypt 형식, 평문 저장 안 함)',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='로그인 아이디 (3~30자, 중복 불가)',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='회원 ID',
               existing_nullable=False)
    op.drop_table_comment(
        'trades',
        existing_comment='체결 (원장). 시장가 즉시 체결이라 주문 하나에 체결 하나',
        schema=None
    )
    op.alter_column('trades', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='체결 시각 (실제 시각)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trades', 'game_tick',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 시각: 그날 몇 번째 5분인지 (0 = 09:00, 78 = 15:30)',
               existing_nullable=False)
    op.alter_column('trades', 'game_day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('trades', 'cash_after',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='체결 직후 예수금 (원). 체결을 순서대로 더하면 이 값과 일치해야 한다',
               existing_nullable=False)
    op.alter_column('trades', 'realized_pnl',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='실현손익 (원, 매도만) = 체결금액 − 수수료 − 거래세 − 평균 매수가 × 수량',
               existing_nullable=True)
    op.alter_column('trades', 'tax',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래세 (원, 매도만, 원 미만 버림)',
               existing_nullable=False)
    op.alter_column('trades', 'fee',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='수수료 (원, 원 미만 버림)',
               existing_nullable=False)
    op.alter_column('trades', 'amount',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='체결금액 = 체결가 × 수량 (원)',
               existing_nullable=False)
    op.alter_column('trades', 'price',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='체결가 (원)',
               existing_nullable=False)
    op.alter_column('trades', 'qty',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='체결 수량 (주)',
               existing_nullable=False)
    op.alter_column('trades', 'side',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='BUY 매수 / SELL 매도',
               existing_nullable=False)
    op.alter_column('trades', 'stock_code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='종목 코드 (stocks.code)',
               existing_nullable=False)
    op.alter_column('trades', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('trades', 'order_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='주문 ID (orders.id). 주문 하나에 체결 하나',
               existing_nullable=False)
    op.alter_column('trades', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='체결 ID',
               existing_nullable=False)
    op.drop_table_comment(
        'stocks',
        existing_comment='가상 종목 마스터. 원본은 simulator/catalog.py 이고 앱이 시작할 때 이 테이블을 맞춘다',
        schema=None
    )
    op.alter_column('stocks', 'hq_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='본사 위치 (국내 지도 핀)',
               existing_nullable=False)
    op.alter_column('stocks', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='회사 소개',
               existing_nullable=False)
    op.alter_column('stocks', 'volatility',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='하루 변동성 (%, 표준편차)',
               existing_nullable=False)
    op.alter_column('stocks', 'beta',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment=None,
               existing_comment='베타: 시장 전체가 1% 움직일 때 평균 몇 % 움직이는지',
               existing_nullable=False)
    op.alter_column('stocks', 'base_price',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 시작 가격의 기준값 (원). 실제 시작가는 ±10% 무작위',
               existing_nullable=False)
    op.alter_column('stocks', 'sector',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='업종. 금리·환율·유가·경기 민감도가 업종별로 다르다',
               existing_nullable=False)
    op.alter_column('stocks', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='종목 이름 (예: 한빛반도체)',
               existing_nullable=False)
    op.alter_column('stocks', 'code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='종목 코드 (예: HBS)',
               existing_nullable=False)
    op.drop_table_comment(
        'stock_prices',
        existing_comment='게임별 일봉 (장 마감 때 기록). 장중 5분 가격은 Redis에만 있다',
        schema=None
    )
    op.alter_column('stock_prices', 'close',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='종가 (원)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='저가 (원)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='고가 (원)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='시가 (원) = 전날 종가',
               existing_nullable=False)
    op.alter_column('stock_prices', 'day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='거래일. 0 이하는 게임 시작 전 30일 차트 (0 = 시작 전날)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'stock_code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='종목 코드 (stocks.code)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.drop_table_comment(
        'portfolio_history',
        existing_comment='장 마감 기준 일별 자산 (자산 그래프·최대 낙폭 계산)',
        schema=None
    )
    op.alter_column('portfolio_history', 'allocation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='종목별 평가액 {종목 코드: 원}',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'stock_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='장 마감 주식 평가액 (원, 종가 기준)',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'cash',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='장 마감 예수금 (원)',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'total',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='장 마감 총자산 (원) = 예수금 + 주식 평가액',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('portfolio_history', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.drop_table_comment(
        'orders',
        existing_comment='주문. 거부된 주문도 사유와 함께 남긴다 (감사 추적)',
        schema=None
    )
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='접수 시각 (실제 시각)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'game_tick',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 시각: 그날 몇 번째 5분인지 (0 = 09:00, 78 = 15:30)',
               existing_nullable=False)
    op.alter_column('orders', 'game_day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('orders', 'client_order_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='클라이언트가 붙인 주문 번호. 같은 게임에서 같은 값이 다시 오면 새로 체결하지 않음 (중복 제출 방지)',
               existing_nullable=True)
    op.alter_column('orders', 'reject_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='거부 사유 (화면에 보여 준 문장)',
               existing_nullable=True)
    op.alter_column('orders', 'reject_code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='거부 사유 코드: INSUFFICIENT_CASH, INSUFFICIENT_QTY, MARKET_CLOSED, UNKNOWN_STOCK 등',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='FILLED 체결 / REJECTED 거부',
               existing_nullable=False)
    op.alter_column('orders', 'qty',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='주문 수량 (주)',
               existing_nullable=False)
    op.alter_column('orders', 'side',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='BUY 매수 / SELL 매도',
               existing_nullable=False)
    op.alter_column('orders', 'stock_code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='종목 코드 (stocks.code). 없는 종목으로 거부된 주문이면 NULL',
               existing_nullable=True)
    op.alter_column('orders', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='주문 ID',
               existing_nullable=False)
    op.drop_table_comment(
        'news_stocks',
        existing_comment='뉴스 ↔ 관련 종목 (다대다)',
        schema=None
    )
    op.alter_column('news_stocks', 'stock_code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='종목 코드 (stocks.code)',
               existing_nullable=False)
    op.alter_column('news_stocks', 'news_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='뉴스 ID (news.id)',
               existing_nullable=False)
    op.drop_table_comment(
        'news',
        existing_comment='플레이어에게 공개된 뉴스',
        schema=None
    )
    op.alter_column('news', 'domestic',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='국내 사건이면 true (국내 지도에 핀)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('news', 'lon',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='경도',
               existing_nullable=True)
    op.alter_column('news', 'lat',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='위도',
               existing_nullable=True)
    op.alter_column('news', 'place',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='사건 장소 이름 (지도 핀)',
               existing_nullable=True)
    op.alter_column('news', 'why',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='해설: 왜 이런 종목이 오르고 내리는지',
               existing_nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('news', 'body',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='본문',
               existing_nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='제목',
               existing_nullable=False)
    op.alter_column('news', 'factor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='관련 가격변동 요인 (/factors 페이지의 항목 id)',
               existing_nullable=True)
    op.alter_column('news', 'tag',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='분류 표시 (금리·환율·유가·공시·실적·루머 등)',
               existing_nullable=False)
    op.alter_column('news', 'kind',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='event 사건 / preview 일정 예고 / info 안내',
               existing_nullable=False)
    op.alter_column('news', 'time',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='화면에 보이는 시각 (예: 10:35, 아침 브리핑은 08:30)',
               existing_nullable=False)
    op.alter_column('news', 'game_tick',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 시각: 그날 몇 번째 5분인지 (0 = 09:00, 78 = 15:30)',
               existing_nullable=False)
    op.alter_column('news', 'day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('news', 'seq',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='게임 안 뉴스 순번 (1부터). 새 뉴스만 받을 때 ?since= 기준',
               existing_nullable=False)
    op.alter_column('news', 'event_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='이 뉴스를 만든 사건 (events.id). 안내·금리 예고처럼 가격 영향이 없으면 NULL',
               existing_nullable=True)
    op.alter_column('news', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('news', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='뉴스 ID',
               existing_nullable=False)
    op.drop_table_comment(
        'market_daily',
        existing_comment='장 마감 기준 시장 지표',
        schema=None
    )
    op.alter_column('market_daily', 'oil',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               comment=None,
               existing_comment='국제유가 (달러/배럴)',
               existing_nullable=False)
    op.alter_column('market_daily', 'fx',
               existing_type=sa.NUMERIC(precision=8, scale=1),
               comment=None,
               existing_comment='원·달러 환율 (원)',
               existing_nullable=False)
    op.alter_column('market_daily', 'base_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='기준금리 (%)',
               existing_nullable=False)
    op.alter_column('market_daily', 'index_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='종합지수 (게임 시작 전날 = 1,000)',
               existing_nullable=False)
    op.alter_column('market_daily', 'day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('market_daily', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.drop_table_comment(
        'holdings',
        existing_comment='보유 종목 (게임별 잔고)',
        schema=None
    )
    op.alter_column('holdings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 변경 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('holdings', 'avg_price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               comment=None,
               existing_comment='평균 매수가 (원, 수수료 제외한 체결가 기준)',
               existing_nullable=False)
    op.alter_column('holdings', 'qty',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='보유 수량 (주). 0이 되면 행을 지운다',
               existing_nullable=False)
    op.alter_column('holdings', 'stock_code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='종목 코드 (stocks.code)',
               existing_nullable=False)
    op.alter_column('holdings', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.drop_table_comment(
        'games',
        existing_comment='게임 한 판. 예수금의 원본. 상태를 바꾸는 요청은 모두 이 행을 SELECT … FOR UPDATE로 잠그고 처리한다',
        schema=None
    )
    op.alter_column('games', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='끝난(또는 포기한) 시각',
               existing_nullable=True)
    op.alter_column('games', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='시작 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('games', 'profile',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='투자 성향 분석 요약 (스타일·점수·특징). 끝난 게임만',
               existing_nullable=True)
    op.alter_column('games', 'final_return_pct',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='최종 수익률 (%). 끝난 게임만',
               existing_nullable=True)
    op.alter_column('games', 'final_total',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='최종 총자산 (원). 끝난 게임만',
               existing_nullable=True)
    op.alter_column('games', 'tax_rate',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               comment=None,
               existing_comment='거래세율 (매도만, 예: 0.002 = 0.2%)',
               existing_nullable=False)
    op.alter_column('games', 'fee_rate',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               comment=None,
               existing_comment='매매 수수료율 (매수·매도 각각, 예: 0.00015 = 0.015%)',
               existing_nullable=False)
    op.alter_column('games', 'cash',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='현재 예수금 (원). 돈의 원본은 이 컬럼이며 Redis 값은 읽을 때마다 여기에 맞춘다',
               existing_nullable=False)
    op.alter_column('games', 'start_cash',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='시작 자금 (원)',
               existing_nullable=False)
    op.alter_column('games', 'max_day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 길이 (거래일)',
               existing_nullable=False)
    op.alter_column('games', 'current_tick',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='현재 시각(틱). Redis 상태가 사라지면 장 시작 지점부터 여기까지 다시 돌려 복구',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::smallint"))
    op.alter_column('games', 'current_day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='현재 거래일 (1 ~ max_day)',
               existing_nullable=False)
    op.alter_column('games', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='ACTIVE 진행 중 / FINISHED 끝까지 마침 / ABANDONED 새 게임을 시작해 포기',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('games', 'seed',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='시장 난수 시드. 같은 시드면 같은 가격·사건이 재현된다 (복구에 사용)',
               existing_nullable=False)
    op.alter_column('games', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='플레이어 (users.id)',
               existing_nullable=False)
    op.alter_column('games', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID',
               existing_nullable=False)
    op.drop_table_comment(
        'game_snapshots',
        existing_comment='복구 지점: 장이 열린 직후의 엔진 상태. Redis 상태가 사라지면 여기서 되살린다',
        schema=None
    )
    op.alter_column('game_snapshots', 'saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='저장 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('game_snapshots', 'state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='엔진 상태 전체 (simulator/engine.py 의 게임 상태 dict)',
               existing_nullable=False)
    op.alter_column('game_snapshots', 'day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='저장한 거래일',
               existing_nullable=False)
    op.alter_column('game_snapshots', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.drop_table_comment(
        'events',
        existing_comment='공개된 사건과 그 영향. 아직 일어나지 않은 사건은 기록하지 않는다 (공정성)',
        schema=None
    )
    op.alter_column('events', 'prices_at',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='사건이 공개된 순간의 종목 가격 {종목 코드: 원}',
               existing_nullable=False)
    op.alter_column('events', 'impacts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='종목별 예상 효과 {종목 코드: %}. 투자 성향 분석(뒤늦은 추격 매수)에 사용',
               existing_nullable=False)
    op.alter_column('events', 'event_key',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='사건 종류 키 (simulator/catalog.py, 예: oil_up)',
               existing_nullable=True)
    op.alter_column('events', 'type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='macro 거시 / corp 기업 공시 / rate 금리 결정 / earnings 실적 / trial 임상 / rumor 루머 / preview 예고',
               existing_nullable=False)
    op.alter_column('events', 'game_tick',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 시각: 그날 몇 번째 5분인지 (0 = 09:00, 78 = 15:30)',
               existing_nullable=False)
    op.alter_column('events', 'day',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='게임 속 거래일 (1부터)',
               existing_nullable=False)
    op.alter_column('events', 'game_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='게임 ID (games.id)',
               existing_nullable=False)
    op.alter_column('events', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='사건 ID',
               existing_nullable=False)
    # ### end Alembic commands ###
